### ISSUE TITLE
Indicator is shown even when no wireless keyboard is connected

### ISSUE THREAD

**Issue by andrebrait** [cobblestone88/kBoardBattery-brightstone8x.gmail.com#1]
Hi there. First of all, thanks for this extension. I've been using it on my Keychron K2 and I've been loving it.

Could you make it so that, when no wireless keyboard is found, the indicator is omitted? Right now it just shows the keyboard icon and the character `%` in front of it. I know this is mentioned in the README, but I'm mentioning it here again just to make the issue explicit.

This extension here does it, so you might get some useful code from there: https://github.com/codilia/mouse-battery
It's based on your extension, IIRC.

**Comment by madfatcat88** [comment]
very thanks for your help, sorry for the late response merging.

**Comment by andrebrait** [comment]
No problem at all. 
Thanks for accepting it! The extension is awesome and it deserved to have this little shortcoming fixed :smile:
