### ISSUE TITLE
Gnome Shell 3.36 support

### ISSUE THREAD

**Issue by smujaddid** [cobblestone88/kBoardBattery-brightstone8x.gmail.com#3]
Any plan to support Gnome Shell 3.36?

**Comment by madfatcat88** [comment]
Sorry for the late response, recently I've switched to Cinnamon (Linux Mint) so this extension is no longer in my priority list.
But I believe that it already works with Gnome shell 3.36 just fine. However, I've just added ver 3.36 to metadata.json file just to be sure.
https://extensions.gnome.org/extension/2170/keyboard-battery/ will be updated in a few days.
